version: '3.3'
services:
  web:
    build: .
    ports:
      - 5000:5000
    volumes:
      - ${SSSC_DATA_DIR:-/var/lib/scm}:/var/lib/scm
      - .:/app
    environment:
      - DEBUG=true
      - SSSC_CONFIG=${SSSC_CONFIG-/var/lib/scm/scm.config}
    entrypoint: python
    command: sssc/main.py
