version: '3.4'
services:
  web:
    ports:
      - 80:80
    volumes:
      - scm-data-prod:/var/lib/scm
    environment:
      - SSSC_CONFIG=${SSSC_CONFIG:-/app/sssc/scm.config}

volumes:
  sssc-data:
    name: scm-data-prod
