# Basic auth
:example-auth := (format "Basic %s" (base64-encode-string (format "%s:%s" "geoffrey.squire@csiro.au" "foobar")))
:alt-auth := (format "Basic %s" (base64-encode-string (format "%s:%s" "geoffrey.squire@gmail.com" "foobar")))

# Get all problems
GET http://localhost:5000/problems/

# Get a problem to sign
GET http://localhost:5000/problems/1

# Test signature
POST http://localhost:5000/signatures/
Authorization: :example-auth
Content-Type: application/json

{
  "entry_id": "http://localhost:5000/problems/1",
  "entry_hash": "ac9b434408d6b191445bee649ec250009569301313e0fdefca785016cc2509dd",
  "signature": "4c4407ccb079d95ae84a5c0afb80f0e5de7620ed3526e4f00df970224fc6dc34d6efb3b3a387b9fd41934cd3dbc8322cc40aa05ac7da451595e4098ec3cec5b2d8689ed6399909ec97c55e9bd753d91616b99e67c5cea895bdb6740b70c99240651de7fbe75400d2ee5f771a47e8fc8682fa147076a39e8e3260d58a33725f3f82d89cb025488f9062fbd42fb44bb9c786ab6a90940f4e9b5d7de483723645e5d7fa29a92dfd03036a315a05bfe77767cabff43a11b97cc58fc051552faed05127d8d48a6288d39cbed945a53a991c3d5a431c6d1015d17af08ba4cab53cb5b5a20635bb3b3e5429c88a95dc2ff6c44732178ff2230bb8c04a0412e5722333f5"
}

# Signatures
GET http://localhost:5000/signatures/

# Signatures
GET http://localhost:5000/signatures/1

# Delete the signature
DELETE http://localhost:5000/signatures/1
Authorization: :example-auth

# Info for user
GET http://localhost:5000/users/1

# New public key for user, using json-merge-patch
PATCH http://localhost:5000/users/1
Authorization: :example-auth
Content-Type: application/merge-patch+json

{
  "public_key": "-----BEGIN RSA PUBLIC KEY-----\nMIIBCgKCAQEAtkDV7IsEmQKta0tGv24BtxcSXwExPKcet4euf3WrgnXasvpPSh8i\nLE1vGspxQPCNwiiHal6kMPfEK1s9kN5wkwq5Fuw8gMCvDvKEkrI+zDz5kk4JvPMT\nT5rec8QUeHtMGX5Gbfg/DrdXT7UUORu0C1rLHb9h+5qOqJHS2G0a5CCLtP1/tc4y\nuBvzAktbu6j9zzQ8mh+qmU+qojJxev3OL4uc4rnYwOuZsHHoGkcNJbTID5em744Y\nlRh4AFiCHOfOysv7OUNXxeytVBE4fgI4gIFpOOOYaFtvgSDMUqy5oM7H9uC7YdXV\n4M5rD4raixHtou89nYSwlh151TNhVr/ejQIDAQAB\n-----END RSA PUBLIC KEY-----\n"
}

# New public key for user, using json
PATCH http://localhost:5000/users/1
Authorization: :example-auth
Content-Type: application/json

{
  "public_key": "Not a valid Public Key! With JSON!"
}

# New public key for user, using unknown type.
PATCH http://localhost:5000/users/1
Authorization: :example-auth

{
  "public_key": "Not a valid Public Key! No content type!"
}

# New public key for user
PUT http://localhost:5000/users/1/public_key
Authorization: :example-auth
Content-Type: application/json

{
  "key": "Not a valid Public Key! With JSON and PUT!"
}

# New public key for user, now with extra plain text
PUT http://localhost:5000/users/1/public_key
Authorization: :example-auth
Content-Type: text/plain

"Not a valid Public Key! With plain text and PUT!"


# Can we still get prov?
GET http://localhost:5000/users/1/prov

# Update a problem
PATCH http://localhost:5000/problems/1
Authorization: :example-auth
Content-Type: application/merge-patch+json

{
  "published": "true"
}
