# Basic auth
:example-auth := (format "Basic %s" (base64-encode-string (format "%s:%s" "geoffrey.squire@csiro.au" "foobar")))

# Get all problems
GET http://localhost:5000/problems/

# Get a problem to sign
GET http://localhost:5000/problems/1

# Test signature
POST http://localhost:5000/signatures/
Authorization: :example-auth
Content-Type: application/json

{
  "entry_id": "http://localhost:5000/problems/1",
  "entry_hash": "68ad13b08e463d1576615b9d9b3eb7820a86761d64e84ae5d9819e17891f1c32",
  "signature": "54731788b88092b7eb6d73e0c38346cca3e54607c4846860df8e188f0ebde345d23008415609921b3d37de512259498a5625ace63036666f3790142df4e3b71659fc616d802c156606dbf013ae322e3984610f579147147675a0213f27f8df9b37c5a6427b6154fa575e0b3dda3e20c7a811e9318d689d89264c3b230298504bd29960708d05ce0f147d050ca7fc62b7bb0b4116c140740367cd30dbbc501676262c00e21b8a9ad9d4b02f8c9561da78b2ad74e06113c6e5ff1e0809c49d9b6d3696ef7e9c319c253381f1dea610de467d58c21de2165efca17565ec465189859350eae2f6d24d44bf1370c6aca88b6488c603a778bbea34eca85fbec4eae7d0"
}

# Signatures
GET http://localhost:5000/signatures/

# Signatures
GET http://localhost:5000/signatures/1

# Delete the signature
DELETE http://localhost:5000/signatures/1
Authorization: :example-auth

# Info for user
GET http://localhost:5000/users/1

# New public key for user, using json-merge-patch
PATCH http://localhost:5000/users/1
Authorization: :example-auth
Content-Type: application/merge-patch+json

{
  "public_key": "-----BEGIN RSA PUBLIC KEY-----\nMIIBCgKCAQEAtkDV7IsEmQKta0tGv24BtxcSXwExPKcet4euf3WrgnXasvpPSh8i\nLE1vGspxQPCNwiiHal6kMPfEK1s9kN5wkwq5Fuw8gMCvDvKEkrI+zDz5kk4JvPMT\nT5rec8QUeHtMGX5Gbfg/DrdXT7UUORu0C1rLHb9h+5qOqJHS2G0a5CCLtP1/tc4y\nuBvzAktbu6j9zzQ8mh+qmU+qojJxev3OL4uc4rnYwOuZsHHoGkcNJbTID5em744Y\nlRh4AFiCHOfOysv7OUNXxeytVBE4fgI4gIFpOOOYaFtvgSDMUqy5oM7H9uC7YdXV\n4M5rD4raixHtou89nYSwlh151TNhVr/ejQIDAQAB\n-----END RSA PUBLIC KEY-----\n"
}

# New public key for user, using json
PATCH http://localhost:5000/users/1
Authorization: :example-auth
Content-Type: application/json

{
  "public_key": "Not a valid Public Key! With JSON!"
}

# New public key for user, using unknown type.
PATCH http://localhost:5000/users/1
Authorization: :example-auth

{
  "public_key": "Not a valid Public Key! No content type!"
}

# New public key for user
PUT http://localhost:5000/users/1/public_key
Authorization: :example-auth
Content-Type: application/json

{
  "key": "Not a valid Public Key! With JSON and PUT!"
}

# New public key for user, now with extra plain text
PUT http://localhost:5000/users/1/public_key
Authorization: :example-auth
Content-Type: text/plain

"Not a valid Public Key! With plain text and PUT!"


# Can we still get prov?
GET http://localhost:5000/users/1/prov
