# Basic auth
:example-auth := (format "Basic %s" (base64-encode-string (format "%s:%s" "geoffrey.squire@csiro.au" "foobar")))

# Get all problems
GET http://localhost:5000/problems/

# Get a problem to sign
GET http://localhost:5000/problems/1

# Test signature
POST http://localhost:5000/signatures/
Authorization: :example-auth
Content-Type: application/json

{
  "entry_id": "http://localhost:5000/problems/1",
  "entry_hash": "67d3d48245a922453af10a2395e10119239b754d8e18ddddf47b2562cbcc806c",
  "signature": "63f950d5198ff830351cfc6d934edfe1ca1d0378be57cadc498a07331d46b1db1ec9afdc75eb297c43b6ea009052555f86644a0e0dc06272936356b8c4e696e8893efceb6866531742cf6b395ccb3525cad662dba0b0b28750469a8cd6672762470fdf1f1a5e6568682462526701b31e0367eac0dc97c05588779a367fdd9f3d8aa979f4cbd57bb10b32aaf0278acfd57a56151a392f2842b3267c39af723f881ab3f7557531963b3ff576a2452695f6a81a6230c879cd5992f94889d93e3ff10df5d93416bdffbcf4995704651081b638afb253ea981c58bce1b3cb6c65af4004f8f894737c4355c91fce866a81e84fe9ef07caa6633be7466e204782ab1b3f"
}

# Signatures
GET http://localhost:5000/signatures/

# Delete the signature
DELETE http://localhost:5000/signatures/1
Authorization: :example-auth

# Info for user
GET http://localhost:5000/users/1

# New public key for user, using json-merge-patch
PATCH http://localhost:5000/users/1
Authorization: :example-auth
Content-Type: application/merge-patch+json

{
  "name": "Geoffrey Squire",
  "public_key": "Not a valid Public Key! again! and again!"
}

# New public key for user, using json
PATCH http://localhost:5000/users/1
Authorization: :example-auth
Content-Type: application/json

{
  "public_key": "Not a valid Public Key! With JSON!"
}

# New public key for user, using unknown type.
PATCH http://localhost:5000/users/1
Authorization: :example-auth

{
  "public_key": "Not a valid Public Key! No content type!"
}

# New public key for user
PUT http://localhost:5000/users/1/public_key
Authorization: :example-auth
Content-Type: application/json

{
  "key": "Not a valid Public Key! With JSON and PUT!"
}

# New public key for user, now with extra plain text
PUT http://localhost:5000/users/1/public_key
Authorization: :example-auth
Content-Type: text/plain

"Not a valid Public Key! With plain text and PUT!"


# Can we still get prov?
GET http://localhost:5000/users/1/prov
