#!/bin/bash
#
# Freeze dependencies for output in requirements.txt.
#
# Removes the sssc package from the list of dependencies if present. Also strips
# pkg-resources if present, which is only introduced due to a bug in Ubuntu (see
# https://bugs.launchpad.net/ubuntu/+source/python-pip/+bug/1635463).
#
# After updating the project dependencies, including version upgrades and/or
# transitive dependencies, regenerate the requirements.txt file with frozen
# versions by running this script.
#

script_dir=$(dirname "$0")
project_dir=$script_dir/..
requirements="${project_dir}/requirements.txt"

echo Freezing dependencies into "${project_dir}/requirements.txt"

pip freeze | grep -v sssc | grep -v "pkg-resources" > $requirements

echo Inserting license info into requirements.txt

"${script_dir}/pylicense.py" $requirements
